version: "3.7"

services:
  database:
    image: postgres
    container_name: database_book
    restart: always    
    ports: 
      - 5433:5433
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=book
      - POSTGRES_DB=book
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: book    
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database

volumes: 
  pgdata:
    driver: local